### ISSUE TITLE
Missing CHANGELOG for 2.0

### ISSUE THREAD

**Issue by nicoddemus** [Bachmann1234/diff-cover#101]
Howdy,

First of all thanks for sharing this tool, it is very useful!

I don't see a CHANGELOG entry for the 2.0 release. Was this an oversight?

Cheers

**Comment by Bachmann1234** [comment]
Last two releases I did not update it. Ill fix that now. I will say despite the major change of version the actual feature functionality change is small.

1.7 was a a bug fix https://github.com/Bachmann1234/diff-cover/issues/93
2.0 was because I broke out diff-cover and diff-quality into separate entry point scripts in a way that could _maybe_ be backwards incompatible (I go over how in the pr https://github.com/Bachmann1234/diff-cover/pull/98 they are both edge cases in my opinion but technically possible?)

**Comment by Bachmann1234** [comment]
Actually looking over this... I have not been updating the changelog in a while. Probably convinced myself that github's releases are good enough. But I should be a tad bit less lazy. ill bring it back up to date

**Comment by Bachmann1234** [comment]
Should be done. Few minors things. Also looks like one update that was made got lost...

**Comment by nicoddemus** [comment]
Thanks @Bachmann1234!

I personally find a CHANGELOG very important. Here's a good reading on the topic in case you haven't seen it yet: https://keepachangelog.com/en/1.0.0/

Cheers, thanks for the great tool!

**Comment by Bachmann1234** [comment]
Thanks! Ill give that a read
