### ISSUE TITLE
adding support on Jacoco report

### ISSUE THREAD

**Issue by patown** [Bachmann1234/diff-cover#82]
Jacoco is quite popular for java code coverage. Hope this tool could add support for Jacoco

**Comment by marklagendijk** [comment]
Because of the lacking mercurial support I created an alternative tool, using Node.js, [diff-test-coverage](https://github.com/Connected-Information-systems/diff-test-coverage).
Supported coverage report formats:
- lcov
- cobertura
- clover
- jacoco
- golang-cover

Supported source control systems:
- Git
- Mercurial
- Anything else that produces unified diffs.

**Comment by Bachmann1234** [comment]
@peterg79 added jacoco support! https://pypi.org/project/diff_cover/1.0.5/
